---
env:
  browser: true

extends:
  - "plugin:compat/recommended"

parserOptions:
  ecmaVersion: 2019
  sourceType: module

plugins:
  - import
  - "@typescript-eslint"

settings:
  polyfills:
    - "Promise" # for op_mini all (opera mini)
