---
env:
  browser: true
  mocha: true
  node: true
  webextensions: true

extends:
  - "airbnb-typescript/base"

parser: "@typescript-eslint/parser"
parserOptions:
  ecmaVersion: 2018
  project:
    - ./config/tsconfig.lint.json

plugins:
  - import
  - "@typescript-eslint"
  - chai-expect
  - chai-friendly
  - mocha-no-only

rules:
  arrow-parens: 0
  class-methods-use-this: 0
  comma-dangle: 0
  consistent-return: 0
  curly: 0
  linebreak-style: 0
  lines-between-class-members: 0
  max-classes-per-file: 0
  max-len: 0
  no-await-in-loop: 0
  no-console:
    - warn
    - allow:
      - warn
      - error
  no-continue: 0
  no-mixed-operators: 0
  no-plusplus:
    - error
    - allowForLoopAfterthoughts: true
  no-restricted-syntax: 0
  no-restricted-exports:
    - error
    - restrictedNamedExports:
      - then
      restrictDefaultExports:
        direct: true
        named: true
        defaultFrom: true
        namedFrom: true
        namespaceFrom: true
  no-underscore-dangle:
    - error
    - allowAfterThis: true
  no-unused-expressions: 0
  nonblock-statement-body-position: 0
  object-curly-newline: 0
  prefer-destructuring: 0
  spaced-comment: 0

  chai-expect/missing-assertion: 2
  chai-expect/terminating-properties: 1

  chai-friendly/no-unused-expressions: 2

  import/no-named-as-default: 0
  import/no-unresolved:
    - error
  import/prefer-default-export: 0

  mocha-no-only/mocha-no-only:
    - error

  "@typescript-eslint/lines-between-class-members":
    - error
    - always
    - exceptAfterSingleLine: true
  "@typescript-eslint/naming-convention":
    - error
    - selector: variable
      format:
        - camelCase
        - UPPER_CASE
        - snake_case
    - selector: function
      format:
        - camelCase
        - PascalCase
      leadingUnderscore: allow
    - selector: typeLike
      format:
        - PascalCase
  "@typescript-eslint/no-unused-vars":
    - error
    - argsIgnorePattern: "^_$"

overrides:
  - files:
    - "*.test.ts"
    - "*.spec?(.*).ts"
    rules:
      '@typescript-eslint/no-unused-expressions': off
